---
title: "CCBER_eDNA"
author: "Ashley Grinstead, Chris Kracha"
date: "06/30/2022"
output: html
---

```{r setup}

library(taxa)
library(metacoder)
library(plyr)
library(janitor)
library(here)
library(tidyverse)


```

# Load in data
```{r clean batch eDNA}

# Function cleans and combines all eDNA files from a folder
eDNA_clean <- function(folder) {
  
  cleaned <- folder %>%
    
    # Create list of all files in target folder
    list.files(full.names = TRUE)  %>%
    
    # Read CSV files and bind rows together
    ldply(read_csv) %>% 
    
    # Remove special characters from column names
    dplyr::rename(percent_match = "% match",
           number_species = "# species") %>%
    
    # Combine taxa into one column
    unite("kpcofgs", Kingdom:Species, sep = ", ", na.rm = TRUE, remove = FALSE) %>%
    
    select(1:number_species, kpcofgs, everything()) %>%
    
    # Switch to long format, where vials are rows not columns
    pivot_longer(cols = 14:ncol(.), 
                 names_to = "sample_id", 
                 values_to = "sample_count") %>%
    
    # Remove rows with no sample count
    filter(sample_count != 0)
  
  return(cleaned)
}
```

```{r load and join to metadata, message=FALSE, include=FALSE}
# 1470 eDNA data with site names
folder1470 <- here::here("data/JVB1470")

JVB1470 <- eDNA_clean(folder1470) %>%
  mutate(site_name = case_when(sample_id == "S034210" ~ "MO1",
                               sample_id == "S034179" ~ "NVBR",
                               sample_id == "XOCTKIVA" ~ "NPB")) %>%
  select(1:sample_count, site_name) %>%
  filter(site_name != "")
  
# 1554 eDNA data with site names
folder1554 <- here::here("data/JVB1554")

info1554 <- read.csv(here::here("data/info_1554.csv")) %>% clean_names()

JVB1554 <- eDNA_clean(folder1554) %>%
  left_join(info1554, by = "sample_id") %>%
  mutate(site_name = case_when(site_name == "Coprvp1" ~ "VP1",
                               site_name == "NWP (NCOS West Pond)" ~ "NWP")) %>%
  select(1:sample_count, site_name) %>%
  filter(site_name != "")

# 1703 eDNA data joined to metadata
folder1703 <- here::here("data/JVB1703")

info1703 <- read_csv(here::here("data/info_1703.csv")) %>% clean_names()

JVB1703 <- eDNA_clean(folder1703) %>% 
  mutate(sample_id = gsub("\\.1", "", sample_id)) %>%
  left_join(info1703, by = "sample_id") %>%
  replace_na(list(site_name = "PIER")) %>%
  select(1:sample_count, site_name) %>%
  filter(site_name != "")

```

```{r bind eDNA batches}

NCOS_eDNA <- bind_rows(JVB1470, JVB1554, JVB1703) %>%
  distinct(ESVId, site_name, .keep_all = TRUE) %>%
  filter(percent_match > 95)
  
```

# Vizualize data
```{r chart of aquatic taxa count}

taxa <- c(rep("order", 3), rep("family", 3), rep("species", 3))
site <- rep(c("NWP" , "VP1", "MO1") , 3)
count <- c(NCOS_eDNA %>% filter(site_name == "NWP") %>% count(Order) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "VP1") %>% count(Order) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "MO1") %>% count(Order) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "NWP") %>% count(Family) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "VP1") %>% count(Family) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "MO1") %>% count(Family) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "NWP") %>% count(Species) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "VP1") %>% count(Species) %>% nrow(),
           NCOS_eDNA %>% filter(site_name == "MO1") %>% count(Species) %>% nrow())
taxa_comparison <- data.frame(taxa, site, count)

ggplot(NCOS_eDNA, aes(x = site_name)) + geom_bar(stat = "count") + ggtitle("Unique DNA Barcode Observations by Site")

ggplot(taxa_comparison, aes(x = taxa, y = count, fill = site)) + 
    geom_bar(position="dodge", stat="identity") + ggtitle("Taxa Counts by Site")
```

```{r aquatic species tree diagrams}

heatTree <- function(input) {
  input %>% parse_tax_data(class_cols = 5:11) %>%
  filter_taxa(taxon_names != "") %>%
  heat_tree(node_label = taxon_names,
            node_color = n_obs,
            node_size = n_obs,
            layout = "da")
}

NCOS_eDNA %>% heatTree()
NCOS_eDNA %>% filter(site_name == "NWP") %>% heatTree()
NCOS_eDNA %>% filter(site_name == "VP1") %>% heatTree()
NCOS_eDNA %>% filter(site_name == "MO1") %>% heatTree()
NCOS_eDNA %>% filter(site_name == "NVBR") %>% heatTree()

```


